---
- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is undefined

- name: Check for Linux
  ansible.builtin.fail:
    msg: This role only supports Linux
  when: ansible_os_family != "Debian"

- name: Set XKBLayout
  ansible.builtin.replace:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT=.*'
    replace: 'XKBLAYOUT="no"'

- name: Generate additional locale in in /etc/locale.gen - "Norwegian"
  ansible.builtin.replace:
    path: /etc/locale.gen
    regexp: '^# {{ linux_language_configuration_default_locale }}'
    replace: '{{ linux_language_configuration_default_locale }}'

#- name: Set xkbmap layout - "Norwegian"
#  ansible.builtin.shell:
#    cmd: echo "setxkbmap no" >> /home/{{ linux_language_configuration_default_username }}/.profile

#- name: Set xkbmap layout - "Norwegian"
#  ansible.builtin.shell:
#    cmd: echo "export LANG=en_US.UTF-8" >> /home/{{ linux_language_configuration_default_username }}/.profile
