- name: Update packages
  ansible.builtin.shell:
    cmd: apt-get -y update
- name: Install Dependencies
  ansible.builtin.shell:
    cmd: apt-get -y install ca-certificates curl gnupg
- name: Install Docker GPG Keys
  ansible.builtin.shell:
    cmd: install -m 0755 -d /etc/apt/keyrings && curl -kfsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && chmod a+r /etc/apt/keyrings/docker.gpg
- name: Add Docker Repo
  ansible.builtin.shell:
    cmd: echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: Update packages Again
  ansible.builtin.shell:
    cmd: apt-get -y update
- name: Install Docker Packages
  ansible.builtin.shell:
    cmd: apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
- name: Install Minikube
  ansible.builtin.shell:
    cmd: curl -kLO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb && dpkg -i minikube_latest_amd64.deb
- name: Add the user 'debian' to primary group of 'docker'
  ansible.builtin.user:
    name: debian
    comment: Debian User
    uid: 1000
    group: docker
- name: Download kubectl
  ansible.builtin.shell:
    cmd: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
- name: Install kubectl
  ansible.builtin.shell:
    cmd: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
- name: Download Helm
  ansible.builtin.shell:
    cmd: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
- name: Install Helm
  ansible.builtin.shell:
    cmd: chmod 700 get_helm.sh && bash get_helm.sh
- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
