---
- name: Setup Debian (sliver C2 installation)
  block:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true

    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - git
          - gpg
          - gpg-agent
          - mingw-w64
          - ca-certificates
          - curl
          - neovim
        state: present
        autoremove: true
        clean: true
      register: result
      retries: 2
      until: result.failed == false

    - name: Download sliver server
      ansible.builtin.get_url:
        url: https://github.com/BishopFox/sliver/releases/download/v1.5.42/sliver-client_linux
        dest: /usr/local/bin/sliver
        mode: '0755'
