---
windows_language_configuration_default_username: 'localuser'
windows_language_configuration_default_display_language: '0409' # US English
windows_language_configuration_default_keyboard_layout: '00000414' # Norwegian