---
- ansible.builtin.set_fact: # if keyboard layout is undefined
    windows_config_keyboard_layout: "{{ windows_config_default['keyboard_layout'] }}"
  when: windows_config['keyboard_layout'] is undefined

- ansible.builtin.set_fact: # if keyboard layout is defined
    windows_config_keyboard_layout: "{{ windows_config['keyboard_layout'] }}"
  when: windows_config['keyboard_layout']

- ansible.builtin.set_fact: # if username is undefined
    windows_config_username: "{{ windows_config_default['username'] }}"
  when: windows_config['username'] is undefined

- ansible.builtin.set_fact: # if username defined
    windows_config_username: "{{ windows_config['username'] }}"
  when: windows_config['username']

- ansible.builtin.set_fact: # if default display language is undefined
    windows_config_display_language: "{{ windows_config_default['display_language'] }}"
  when: windows_config['display_language'] is undefined

- ansible.builtin.set_fact: # if default display language is defined
    windows_config_display_language: "{{ windows_config['display_language'] }}"
  when: windows_config['display_language']

- name: Set default keyboard in registry
  ansible.windows.win_powershell:
    script: |
      reg add "HKEY_USERS\.DEFAULT\Keyboard Layout\Preload" /v 1 /d {{ windows_config_keyboard_layout }} /f

- name: Set users' default keyboard in registry
  ansible.windows.win_powershell:
    script: |
      reg add "HKEY_USERS\$(Get-Localuser | Where-Object -Property Name -eq {{ windows_config_username }}
      | Select-Object -First 1 -ExpandProperty sid)\Keyboard Layout\Preload" /v 1 /d {{ windows_config_keyboard_layout }} /f

- name: Set language+keyboard combination
  ansible.windows.win_powershell:
    script: |
      Set-WinDefaultInputMethodOverride -InputTip "{{ windows_config_display_language }}:{{ windows_config_keyboard_layout }}"

- name: Set language+keyboard combination for everything
  ansible.windows.win_powershell:
    script: |
      Copy-UserInternationalSettingsToSystem -NewUser $True -WelcomeScreen $True

- name: Reboot after changing keyboard layout
  ansible.windows.win_reboot:
    # reboot_timeout: 3600
