---
- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is not defined

- name: Check for Windows
  ansible.builtin.fail:
    msg: This role only supports Windows
  when: ansible_os_family != "Windows"

- name: Configure language - Windows
  ansible.builtin.include_tasks:
    file: keyboard.yml
