---
- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is not defined

- name: Check for Windows
  ansible.builtin.fail:
    msg: This role only supports Windows
  when: ansible_os_family != "Windows"

- name: Configure keyboard
  ansible.builtin.include_tasks:
    file: keyboard.yml
  when: windows_config['keyboard_layout'] is defined

- name: Get Zimmerman Tools
  ansible.builtin.include_tasks:
    file: zimmerman.yml
  when: windows_config['get_zimmerman_tools']
