---
# mod env path: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_path_module.html#ansible-collections-ansible-windows-win-path-module
# mod env vars: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_environment_module.html

- name: Setting facts
  ansible.builtin.set_fact: # url and out path
    url: "https://github.com/EricZimmerman/Get-ZimmermanTools/blob/master/Get-ZimmermanTools.ps1"
    dest: "C:/Tools/"
  when:
    - windows_config['get_zimmerman_url'] is undefined
    - windows_config['get_zimmerman_dest'] is undefined

- name: Download Get-ZimmermanTools.ps1 to {{ dest }}
  ansible.windows.win_powershell:
    script: |
      Invoke-WebRequest -Uri $Url -OutFile $Dest
    parameters:
      Url: "{{ url }}"
      Dest: "{{ dest }}"

- name: Create C:/Temp/ directory
  ansible.windows.win_file:
    path: C:/Temp/
    state: directory

# recurse over directories within "dest": 
- name: Copy script
  ansible.windows.win_copy:
    src: "files/list_paths.ps1"
    dest: C:/Temp/list_paths.ps1

- name: Register additional tool paths
  ansible.windows.win_powershell:
    script: |
      C:/Temp/list_paths.ps1
    executable: pwsh.exe
    arguments:
      - -ExecutionPolicy
      - ByPass
    parameters:
      Dest: "{{ dest }}/net6"
    register: pwsh_output

#- name: Recursively append tool paths to users env
#  ansible.windows.win_powershell:
#    script: |
#      Get-ChildItem "{{ dest }}" -Recurse -Depth 1
#      | Foreach-Object { if ( Test-Path -Path $_.FullName -PathType Container ) 
#         { $Env:PATH += ";$($_.FullName)" }
#      };
#      [Environment]::SetEnvironmentVariable("Path", "$Env:PATH", "User")
#    register: additional_usr_paths

- name: Debug additional paths
  ansible.builtin.debug:
    msg: "PATH: {{ pwsh_output }}"

#- name: Ensure that {{ dest }} is present in the current user's PATH
#  ansible.windows.win_path:
#    name: PATH
#    elements: "{{ additional_usr_paths }}"
#    scope: user
#    state: present