---
# mod env path: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_path_module.html#ansible-collections-ansible-windows-win-path-module
# mod env vars: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_environment_module.html

- name: Setting facts
  when:
    - windows_config['get_zimmerman_url'] is undefined
    - windows_config['get_zimmerman_dest'] is undefined
  ansible.builtin.set_fact: # url and out path
    url: "https://github.com/EricZimmerman/Get-ZimmermanTools/blob/master/Get-ZimmermanTools.ps1"
    dest: "C:/Tools/"

- name: Download Get-ZimmermanTools.ps1 to {{ dest }}
  ansible.windows.win_powershell:
    script: |
      Invoke-WebRequest -Uri "https://github.com/EricZimmerman/Get-ZimmermanTools/blob/master/Get-ZimmermanTools.ps1" -OutFile C:\Tools\Get-ZimmermanTools.ps1

- name: Register additional tool paths
  ansible.windows.win_powershell:
    script: | 
      pwsh.exe C:\Tools\Get-ZimmermanTools.ps1
    executable: pwsh.exe
    arguments:
      - -ExecutionPolicy
      - ByPass

- name: Append net6 path to users env
  ansible.windows.win_powershell:
    script: |
      $Env:PATH += ";{{ dest }}"

- name: Recursively append tool paths to users env
  ansible.windows.win_powershell:
    script: |
      Get-ChildItem "{{ dest }}/net6/" -Recurse -Depth 1 | Foreach-Object { if ( Test-Path -Path $_.FullName -PathType Container ) { $Env:PATH += ";$($_.FullName)" }}; [Environment]::SetEnvironmentVariable("Path", "$Env:PATH", "User")