---
- name: Install kali packages
  become: true
  ansible.builtin.apt:
    name:
      - git
      - python3-pip
      - jq
      - curl
      - dbus
      - dbus-user-session
      - dbus-x11
      - vim
      - kali-defaults
      - kali-root-login
      - desktop-base
      - wget
      #- kali-linux-core
      #- kali-linux-default # This takes forever (2+ hours) and really slows down template building
    state: present
  register: result
  retries: 2
  until: result.failed == false
  
- name: Install xrdp and dependencies
  become: true
  ansible.builtin.apt:
    name:
      - kali-desktop-xfce
      - xorg
      - xrdp
    state: present
  register: result
  retries: 2
  until: result.failed == false

#- name: Set XRDP port 3390
#  become: true
#  ansible.linux.shell:
#    script: |
#      sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini

- name: Enable the xrdp.service
  become: true
  ansible.builtin.service:
    name: xrdp.service
    enabled: true
    daemon_reload: true
