roles:
  - ludus_local_users
role_vars:
  ludus_local_users:
    - login: jdoe
      password: aA8MaQ2alStPYAFh
      groups: sudo
      sudo_nopasswd: true
    - login: msmith
      password: 25H60eORSggFfH2Y
