roles:
  - ludus_local_users
role_vars:
  ludus_local_users:
    - login: SQLservice
      password: 5tB8zRggjI7da4kdExHC
  ludus_local_groups:
    - name: Administrators
      members:
        - local-adm
    - name: Remote Desktop Users
      members:
        - MYRANGE\Developers
        - MYRANGE\Tier 1 Admins
