---
- ansible.builtin.set_fact: # if keyboard layout is undefined
    windows_config_keyboard_layout: "{{ windows_config_default['keyboard_layout'] }}"
  when: windows_config['keyboard_layout'] is undefined

- ansible.builtin.set_fact: # if keyboard layout is defined
    windows_config_keyboard_layout: "{{ windows_config['keyboard_layout'] }}"
  when: windows_config['keyboard_layout'] is defined

- ansible.builtin.set_fact: # if username is undefined
    windows_config_username: "{{ windows_config_default['username'] }}"
  when: windows_config['username'] is undefined

- ansible.builtin.set_fact: # if username defined
    windows_config_username: "{{ windows_config['username'] }}"
  when: windows_config['username'] is defined

- ansible.builtin.set_fact: # if default display language is undefined
    windows_config_display_language: "{{ windows_config_default['display_language'] }}"
  when: windows_config['display_language'] is undefined

- ansible.builtin.set_fact: # if default display language is defined
    windows_config_display_language: "{{ windows_config['display_language'] }}"
  when: windows_config['display_language'] is defined


