---
- name: Setup Kali (install xrdp)
  hosts: all
  become_method: sudo
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - git
          - python3-pip
          - jq
          - curl
          - dbus
          - dbus-user-session
          - dbus-x11
          - vim
          - swapspace # helps with machines with low RAM
          - kali-defaults
          - kali-root-login
          - desktop-base
          - wget
          - kali-linux-core
          - kali-desktop-xfce
          - xorg
          - xrdp
          # - kali-linux-default # This takes forever (2+ hours) and really slows down template building
        state: present
      register: result
      retries: 2
      until: result.failed == false

    - name: Enable the xrdp.service
    become: true
    ansible.builtin.service:
      name: xrdp.service
      enabled: true
      daemon_reload: true
      state: started