---
- name: Check if the "installed.txt" file exists
  win_stat: path="C:\SysmonFiles\installed.txt"
  register: stat_installed

- name: Check if the sysmon installation has been completed
  when: stat_installed.stat.exists == False
  block:
    - name: Check if the "C:\SysmonFiles" directory exists
      win_stat: path="C:\SysmonFiles"
      register: stat_dir

    - name: Create SysmonFiles Directory
      when: stat_dir.stat.exists == False
      ansible.windows.win_shell: New-Item -ItemType Directory -Path "C:\SysmonFiles"

    - name: Check if the "Sysmon.exe" executable exists
      win_stat: path="C:\SysmonFiles\Sysmon.exe"
      register: stat_exe

    - name: Download Sysmon Executable
      when: stat_exe.stat.exists == False
      ansible.windows.win_shell: Invoke-WebRequest -UseBasicParsing -Uri https://live.sysinternals.com/Sysmon.exe -OutFile "C:\SysmonFiles\Sysmon.exe"

    - name: Check if the "sysmonconfig.xml" config exists
      win_stat: path="C:\SysmonFiles\sysmonconfig.xml"
      register: stat_xml

    - name: Download Sysmon Config File
      when: stat_xml.stat.exists == False
      ansible.windows.win_shell: Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/Antonlovesdnb/ConstructingDefense/main/sysmonconfig.xml -OutFile "C:\SysmonFiles\sysmonconfig.xml"

    - name: Install Sysmon
      ansible.windows.win_shell: C:\SysmonFiles\Sysmon.exe -accepteula -i C:\SysmonFiles\sysmonconfig.xml
      args:
        executable: cmd

    - name: Create "installed.txt"
      win_file:
        path: "C:\\SysmonFiles\\installed.txt"
        state: touch
