---
- name: Setup UFW on Linux
  hosts: all
  become_method: sudo
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - ufw
        state: present
      register: result
      retries: 2
      until: result.failed == false

    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        rule: allow
    
    - name: Allow all access to port 22 (SSH)
      community.general.ufw:
        rule: allow
        name: '22'
      
    - name: Allow all access to port 3389 (xrdp)
      community.general.ufw:
        rule: allow
        port: '3389'

    - name: Successfully installed and configured UFW
      ansible.builtin.debug:
        msg: "Successfully installed UFW"
