---
- name: Gather facts if needed
  when: ansible_os_family is undefined
  ansible.builtin.setup:

- name: Check for Linux
  when: ansible_os_family != "Debian"
  ansible.builtin.fail:
    msg: This role only supports Debian Linux

#- name: Sliver Main - Debug variables
#  debug:
#    msg:
#      - "ansible_os_family: {{ ansible_os_family }}"
#      - "ludus_install_sliver: {{ ludus_install_sliver }}"
#      - "ludus_install_sliver.server: {{ ludus_install_sliver.server }}"
#      - "ludus_install_sliver.port: {{ ludus_install_sliver.port }}"
#      - "ludus_install_sliver.client: {{ ludus_install_sliver.client }}"
#      - "ludus_install_sliver.metasploit: {{ ludus_install_sliver.metasploit }}"

- name: Install sliver
  when: ansible_os_family == "Debian"
  block:
    - name: Apt update cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      register: result
      retries: 2
      until: result.failed == false

    - name: Apt install requirements
      become: true
      ansible.builtin.apt:
        name:
          - git
          - gpg
          - gpg-agent
          - mingw-w64
          - ca-certificates
          - curl
        state: present
      register: result
      retries: 2
      until: result.failed == false

    - name: Install sliver-client
      when: ludus_install_sliver.client is true
      include_tasks: client.yml

    - name: Install sliver-server
      when: ludus_install_sliver.server is true
      include_tasks: server.yml
