---
- name: Install ufw
  become: true
  ansible.builtin.apt:
    name:
      - ufw
    state: present
  register: result
  retries: 2
  until: result.failed == false

- name: Enable UFW # and deny any
  community.general.ufw:
    state: enabled
    rule: allow

#- name: Allow all access to port OpenSSH (22)
#  community.general.ufw:
#    rule: allow
#    name: OpenSSH
  
#- name: Allow all access to port 3389 (xrdp)
#  community.general.ufw:
#    rule: allow
#    port: '3389'

- name: Successfully installed and configured UFW
  ansible.builtin.debug:
    msg: "Successfully installed UFW"
