---
- name: Debugging "{{ keyboard.layout[0] }}"
  debug:
    msg: "{{ keyboard.layout[0] }}"

- name: Set XKBLAYOUT to "{{ keyboard.layout[0] }}" in /etc/default/keyboard
  become: true
  ansible.builtin.shell: sed -i 's/^XKBLAYOUT=.*/XKBLAYOUT="{{ keyboard.layout[0] }}"/' /etc/default/keyboard

- name: Set xkbmap layout to "{{ keyboard.layout[0] }}"
  ansible.builtin.shell: | 
    echo "setxkbmap {{ keyboard.layout[0] }}" >> /home/{{ username }}/.profile

#- name: Set xkbmap layout to "{{ keyboard.layout[0] }}"
#  ansible.builtin.shell: setxkbmap {{ keyboard.layout[0] }}
