---
#- set_fact:
#    keyboard_layout: "{{ default_keyboard_layout }}"
#  when: linux_keyboard_language is undefined

#- set_fact:
#    linux_username: "{{ ludus_default_linux_username }}"
#  when: linux_username is undefined

- name: Set default keyboard language to "{{ keyboard_layout }}"
  become: true
  ansible.linux.shell:
    script: |
      sed -i 's/^XKBLAYOUT=.*/XKBLAYOUT="{{ keyboard_layout }}"/' /etc/default/keyboard

- name: Set XKBMap Layout to "{{ keyboard_layout }}"
  ansible.linux.shell:
    script: |
      setxkbmap "{{ keyboard_layout }}"

#- name: Linux - Success
#  ansible.builtin.debug:
#    msg: "Default keyboard layout has changed"
