---
- name: Configure keyboard layout
  ansible.builtin.include_tasks:
    file: keyboard.yml
  when: linux_config.keyboard_layout is defined

- name: Configure rdp
  ansible.builtin.include_tasks:
    file: rdp.yml
  when: linux_config.rdp is defined

- name: Install packages
  ansible.builtin.include_tasks:
    file: packages.yml
  when: linux_config.packages is defined
