---
- name: Configure keyboard layout
  ansible.builtin.include_tasks:
    file: keyboard.yml
  when: keyboard is defined

- name: Configure rdp
  ansible.builtin.include_tasks:
    file: rdp.yml
  when: rdp is defined
