---
- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is undefined

- name: Debug Task
  when: linux_config_debug is defined
  block:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Debug os family
      ansible.builtin.debug:
        msg: "{{ ansible_os_family }} {{ ansible_facts['ansible_lsb']['release'] }}"

- name: Check for Linux
  ansible.builtin.fail:
    msg: This role only supports Linux
  when: ansible_os_family != "Debian"

- name: Configure keyboard layout
  ansible.builtin.include_tasks:
    file: keyboard.yml
  when: linux_config['keyboard_layout'] is defined

- name: Configure rdp
  ansible.builtin.include_tasks:
    file: rdp.yml
  when: linux_config['rdp'] is defined

# - name: Install packages
#  ansible.builtin.include_tasks:
#    file: packages.yml
#  when: linux_config['packages'] is defined # This does not work as expected
