---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 5400

- name: Apt install {{ packages }}
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  with_items: "{{ packages }}"
  register: result
  retries: 2
  until: result.failed == false
  when: ansible_os_family == "Debian"
