---
- name: Debian facts
  when: # ansible_os_family == Debian AND rdp != kali
    - ansible_os_family == "Debian"
    - linux_config['kali'] is undefined # This should not be defined for non-kali hosts
  ansible.builtin.set_fact:
    linux_rdp_dependencies:
      - xorg
      - xrdp
      - task-xfce-desktop

- name: Ubuntu 20.04 facts
  become: true
  when: # ansible_os_family == Debian AND rdp != kali
    - ansible_os_family == "Debian"
    - ansible_facts['lsb']['release'] == "20.04"
  block:
    - name: Listing dependencies
      ansible.builtin.set_fact:
        linux_rdp_dependencies:
          - xorg
          - xrdp
          - xfce4
          - xubuntu-desktop
          - xfce4-goodies
    - name: Add xrdp user to ssl-cert group
      ansible.builtin.user:
        name: xrdp
        groups: ssl-cert
        append: true
    - name: Add {{ linux_config_username }} user to ssl-cert group
      ansible.builtin.user:
        name: "{{ linux_config_username }}"
        groups: ssl-cert
        append: true
#    - name: Add {{ linux_config_username }} user to ssl-cert group
#      ansible.builtin.user:
#        name: "remnux"
#        groups: ssl-cert
#        append: true

- name: Kali facts
  when:
    - linux_config['kali'] is defined # This should only be defined for kali hosts
  ansible.builtin.set_fact:
    linux_rdp_dependencies:
      - kali-desktop-xfce
      - xorg
      - xrdp

- name: Apt install rdp dependencies
  when:
    - ansible_os_family == "Debian"
  ansible.builtin.include_tasks: packages.yml
  vars:
    packages: "{{ linux_rdp_dependencies }}"

- name: Disable the kasmvnc service
  when:
    - linux_config['kali'] is defined
  become: true
  ansible.builtin.service:
    name: kasmvnc@1.service
    daemon_reload: true
    state: stopped
    enabled: false

- name: Enable the xrdp.service
  become: true
  ansible.builtin.service:
    name: xrdp.service
    daemon_reload: true
    enabled: true
    state: started
