---
- ansible.builtin.set_fact:
    dependencies: 
      - xorg
      - xrdp
      - task-xfce-desktop
  when: # ansible_os_family == Debian AND rdp != kali
    - ansible_os_family == "Debian"
    - rdp.distro != "kali" 

- ansible.builtin.set_fact:
    dependencies: 
      - kali-desktop-xfce
      - xorg
      - xrdp
  when: # ansible_os_family == Debian AND rdp == kali
    - ansible_os_family == "Debian"
    - rdp.distro == "kali"

- name: Apt install dependencies
  ansible.builtin.include_tasks:
    file: apt.yml
  when: ansible_os_family == "Debian"

- name: Disable the kasmvnc service
  become: true
  ansible.builtin.service:
    name: kasmvnc@1.service
    daemon_reload: true
    enabled: false
    state: stopped

- name: Enable the xrdp.service
  become: true
  ansible.builtin.service:
    name: xrdp.service
    daemon_reload: true
    enabled: true
    state: started
